# Generated by Django 2.1.5 on 2019-02-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprogress',
            name='theme',
        ),
        migrations.AddField(
            model_name='playerprogress',
            name='themes',
            field=models.ManyToManyField(to='accueil.Theme'),
        ),
    ]
