# Generated by Django 2.1.5 on 2019-03-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0003_customuser_themes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprogress',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerprogress',
            name='themes',
        ),
        migrations.DeleteModel(
            name='PlayerProgress',
        ),
    ]
