# Generated by Django 2.1.5 on 2019-01-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='top_score',
            field=models.IntegerField(default=0, verbose_name='high score'),
        ),
    ]
